# Generated by Django 4.2.3 on 2023-10-07 12:13

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0002_rename_cover_image_user_cover_pic_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="gender",
            field=models.CharField(blank=True, default="male", max_length=200),
        ),
    ]
