# Generated by Django 4.2.3 on 2023-10-07 05:57

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Comment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("body", models.TextField()),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("isEdited", models.BooleanField(blank=True, default=False, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="Tweet",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("username", models.TextField(blank=True)),
                ("body", models.TextField(blank=True)),
                (
                    "image",
                    models.ImageField(blank=True, null=True, upload_to="tweetspic"),
                ),
                ("is_parent", models.BooleanField(blank=True, default=True, null=True)),
                ("share_count", models.IntegerField(blank=True, default=0, null=True)),
                (
                    "is_private",
                    models.BooleanField(blank=True, default=False, null=True),
                ),
                ("isEdited", models.BooleanField(blank=True, default=False, null=True)),
                ("updated", models.DateTimeField(auto_now=True)),
                ("created", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Tweet",
                "verbose_name_plural": "Tweets",
                "ordering": ["-created"],
            },
        ),
    ]
