# Generated by Django 4.2.3 on 2023-10-07 12:16

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tweets", "0002_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="tweet",
            name="gender",
            field=models.CharField(blank=True, default="male", max_length=200),
        ),
    ]
