# Generated by Django 4.2.3 on 2023-10-09 14:17

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tweets", "0003_tweet_gender"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tweet",
            name="gender",
            field=models.CharField(blank=True, default="female", max_length=200),
        ),
    ]
