# Generated by Django 4.2.3 on 2023-10-14 13:39

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):
    dependencies = [
        ("tweets", "0004_alter_tweet_gender"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="comment",
            name="author",
        ),
        migrations.RemoveField(
            model_name="comment",
            name="parent",
        ),
        migrations.RemoveField(
            model_name="comment",
            name="post",
        ),
        migrations.AddField(
            model_name="comment",
            name="gender",
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name="comment",
            name="tweet_uuid",
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name="tweet",
            name="uuid",
            field=models.UUIDField(default=uuid.uuid4, unique=True),
        ),
    ]
