# Generated by Django 4.2.3 on 2023-10-14 15:41

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tweets", "0005_remove_comment_author_remove_comment_parent_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="comment",
            name="isEdited",
        ),
        migrations.RemoveField(
            model_name="comment",
            name="liked",
        ),
        migrations.AddField(
            model_name="comment",
            name="username",
            field=models.TextField(blank=True),
        ),
        migrations.RemoveField(
            model_name="tweet",
            name="liked",
        ),
        migrations.AddField(
            model_name="tweet",
            name="liked",
            field=models.CharField(blank=True, max_length=3000),
        ),
    ]
