# Generated by Django 4.2.3 on 2023-10-07 05:57

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Notification",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "notification_type",
                    models.CharField(
                        choices=[
                            ("L", "love"),
                            ("F", "follow"),
                            ("M", "message"),
                            ("R", "reply"),
                            ("RT", "retweet"),
                            ("LR", "love_comment"),
                        ],
                        default=None,
                        max_length=2,
                    ),
                ),
                ("date", models.DateTimeField(auto_now_add=True)),
                ("user_has_seen", models.BooleanField(default=False)),
            ],
        ),
    ]
