# Generated by Django 4.2.3 on 2023-10-14 12:44

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Comment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("body", models.TextField(blank=True)),
                ("username", models.TextField(blank=True)),
                ("gender", models.CharField(blank=True, max_length=200)),
                ("post_uuid", models.CharField(blank=True, max_length=200)),
                ("created", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="Post",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("username", models.TextField(blank=True)),
                ("body", models.TextField(blank=True)),
                ("liked", models.CharField(blank=True, max_length=3000)),
                (
                    "image",
                    models.ImageField(blank=True, null=True, upload_to="tweetspic"),
                ),
                ("gender", models.CharField(blank=True, max_length=200)),
                ("uuid", models.UUIDField(default=uuid.uuid4, unique=True)),
            ],
            options={
                "verbose_name": "Post",
                "verbose_name_plural": "Posts",
            },
        ),
    ]
