# Generated by Django 4.2.3 on 2023-10-13 13:18

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):
    dependencies = [
        ("community", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="comment",
            name="gender",
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name="post",
            name="uuid",
            field=models.UUIDField(default=uuid.uuid4, unique=True),
        ),
        migrations.AlterField(
            model_name="post",
            name="gender",
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
